#ifndef _NGX_STREAM_SOCKS5_
#define _NGX_STREAM_SOCKS5_


#define NGX_STREAM_SOCKS5_UNAUTHORIZED              401
#define NGX_STREAM_SOCKS5_FORBIDDEN                 403
#define NGX_STREAM_SOCKS5_NOT_ALLOWED               405
#define NGX_STREAM_SOCKS5_REQUEST_TIME_OUT          408

#endif /* _NGX_STREAM_SOCKS5_ */
